# Generated by Django 5.0.7 on 2024-07-21 03:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('assunto', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('RESPONDER', 'RESPONDER'), ('RESPONDIDO', 'RESPONDIDO')], default='RESPONDER', max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 21, 0, 0, 7, 774343), null=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(default='user-default.png', upload_to='')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('titulo', models.CharField(blank=True, max_length=600, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, choices=[('Apartamento', 'Apartamento'), ('Casa/Sobrado', 'Casa/Sobrado'), ('Terreno', 'Terreno')], max_length=100, null=True)),
                ('objetivo', models.CharField(blank=True, choices=[('VENDA', 'VENDA'), ('ALUGA', 'ALUGA')], max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 21, 0, 0, 7, 773347), null=True)),
                ('endereco', models.CharField(blank=True, max_length=600, null=True)),
                ('cidade', models.CharField(blank=True, default='Paranavaí-PR', max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('qtde_quartos', models.IntegerField(default=0)),
                ('qtde_suites', models.IntegerField(default=0)),
                ('qtde_banheiros', models.IntegerField(default=0)),
                ('qtde_vagas', models.IntegerField(default=0)),
                ('qtde_vagas_coberta', models.IntegerField(default=0)),
                ('area_total', models.IntegerField(default=0)),
                ('area_construida', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='ImovelContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('assunto', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('RESPONDER', 'RESPONDER'), ('RESPONDIDO', 'RESPONDIDO')], default='RESPONDER', max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 21, 0, 0, 7, 773347), null=True)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.imovel')),
            ],
            options={
                'verbose_name': 'Contato pelo Imóvel',
                'verbose_name_plural': 'Contatos pelo Imóveis',
            },
        ),
        migrations.CreateModel(
            name='ImovelFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.imovel')),
            ],
        ),
    ]
