# Generated by Django 5.0.7 on 2024-07-22 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_bairro_alter_contato_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='isHomepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 22, 10, 45, 5, 476521), null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 22, 10, 45, 5, 474526), null=True),
        ),
        migrations.AlterField(
            model_name='imovelcontato',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 22, 10, 45, 5, 475524), null=True),
        ),
    ]
